### ISSUE TITLE
Response for unfound resource not JSON

### ISSUE THREAD

**Issue by MatrixStefan** [XeroAPI/Xero-OpenAPI#163]
When getting a single contact, if the resource can't be found, the API doesn't return usable JSON data. Instead it returns a string.

For example:
https://api.xero.com/api.xro/2.0/Contacts/some-imaginary-uuid

Response:
`The resource you're looking for cannot be found`

Please update this so the response is in a format consistent with the rest of the API, such as:

`{  
  "Status": "Not Found",  
  "Errors": [  
    {  
        "Message": "The resource you're looking for cannot be found"  
    }  
  ]  
}`

...or something 🙂

**Comment by SidneyAllen** [comment]
@MatrixStefan 

Thanks for the feedback - I will pass this along to our API team.  This issue is not something we can address in our OpenAPI specs or SDKs.  Our APIs have been around much longer than these specifications and therefore we do not create or update our APIs from these specs (it's the other way around).  We've written these OAS in order to generate SDKs to interact with existing APIs.

You can voice your feedback in a different forum so other developers can vote as well at https://xero.uservoice.com/forums/5528-xero-accounting-api

I'll be closing this issue now.
