### ISSUE TITLE
Accounting invoices date issue

### ISSUE THREAD

**Issue by ksaritek** [XeroAPI/Xero-OpenAPI#184]
Hi, 

I used open API generator to generate Go code and invoice is not parsed properly. There seems a bug for UpdatedDateUTC
```
Generated Part of Go Code
// Invoice struct for Invoice
type Invoice struct {
        ....
	// Last modified date UTC format
	UpdatedDateUTC time.Time `json:"UpdatedDateUTC,omitempty"`
	....
}
```

https://developer.xero.com/documentation/api/invoices

`UpdatedDateUTC | Last modified date UTC format`

but in the demo, it seem invalid format in json 
```
"UpdatedDateUTC": "\/Date(1518685950940+0000)\/",
``` 

the error message I got
```
err: parsing time ""\/Date(1229650679057+0000)\/"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "\/Date(1229650679057+0000)\/"" as "2006"
```

**Comment by SidneyAllen** [comment]
Hi @ksaritek 

We are aware that standard code generators don't handle the MS Dateformat that we return from our Accounting APIs.

We are building our SDKs from these OpenAPI specs and have modified our mustache templates to work around these and convert them into native date or date-time.  We do have plans to remove the format: date and format: date-time in the future so these would be simple "strings".  This change isn't happening yet as we need to modify our mustache templates for 5 SDKs to use vendorExtensions and not rely on the format:date and date-time.

Of course, once the change is done you'd still have to handle the conversion of these strings into dates, but it should allow for code generation.

Final caveat, our Accounting API is over a decade old and predates Swagger and OpenAPI specs.  For this reason, we've been reverse engineering these specs.  There are inherent quirks in our APIs that are not easily addressed in OpenAPI specs and therefore your mileage may vary when using an off the shelf code generator.

**Comment by ksaritek** [comment]
Hi @SidneyAllen, Thanks for the reply. So I will do the same modification for the GoLang, right? 

```
Final caveat, our Accounting API is over a decade old and predates Swagger and OpenAPI specs. For this reason, we've been reverse engineering these specs. There are inherent quirks in our APIs that are not easily addressed in OpenAPI specs and therefore your mileage may vary when using an off the shelf code generator.
```
Up to your comment, should I continue with OpenAPI specs or not? I confused a little bit.

**Comment by SidneyAllen** [comment]
@ksaritek - Not sure what you mean by same modification.  If you have access to the mustache templates you are using to generate the code, then YES, you can make modifications.  Some folks are using online code generators and don't have that option.

In the near term, if you want to fork this repo and wish to find and remove all format: date and format: date-time you are free too.  We will be making that change in the future.

Yes, you can continue to use the OpenAPI spec, but I want to be fully transparent that there are quirks in the API - but for the most part it should work (heck we are using it to generate our SDKs 😄 )

For example our Invoices endpoints supports getting and invoice as JSON OR as a PDF.  But with strongly typed language you need to pick one and OpenAPI spec only allows a path to be defined once in a spec.

So,  "getInvoiceAsPDF" is a method that uses the path /invoices/{invoiceID}/pdf  (and we added a vendor extension x-path: /invoices/{invoiceID}.  In our template if x-path exists, we substitute it for the defined path.

I'm not trying to worry you because the spec should mostly work for you and using standard templates (once the date issue is sorted) but there may be other things we've worked around.

Hope that clarifies things.

**Comment by ksaritek** [comment]
👍 yep that clarifies things

**Comment by SidneyAllen** [comment]
@ksaritek - hope you are well.

I've begun work to changing MSJSON dates into just Strings in our OpenAPI spec.

Here is my work in progress - branch
https://github.com/XeroAPI/Xero-OpenAPI/tree/accounting-date-as-string

In the future we'll merge this into master, but I don't have an ETA yet.
