### ISSUE TITLE
Plans to officially host on SwaggerHub?

### ISSUE THREAD

**Issue by MatthewSteeples** [XeroAPI/Xero-OpenAPI#204]
The readme refers to using SwaggerHub to browse the spec, so I was wondering if there were any plans to have an `official` copy of the spec hosted there? There are at least 4 unofficial versions uploaded by other developers, and I think it could end up leading to some confusion

**Comment by SidneyAllen** [comment]
@MatthewSteeples - While we created our spec on SwaggerHub, we found our Accounting API spec so large that the editor became sluggish and would hang.  I think this is because every character you type triggers a validation and re rendering.

For this reason, we've moved to VSCode to edit and merge changes into GitHub.

If there is a way for SwaggerHub to consume a yaml file from our existing Repo, let us know.

**Comment by MatthewSteeples** [comment]
@SidneyAllen There is. You can either feed your YAML file into SwaggerHub (and it supports listening to a GitHub repo for changes so it can auto update) or you can actually host it on any static site - Eg https://cloudflare-ipfs.com/ipfs/QmfCqx45GnuhWsVp5BaWwLDBhRzvkSFU1vNToobfxosoME/

The files required actually build the page from the YAML on demand, so there's no rebuild required

**Comment by SidneyAllen** [comment]
@MatthewSteeples - you'll have to share more specific instructions. I just looked at SwaggerHub docs and it says the GitHub sync is one-way ... from SwaggerHub TO a GitHub repository and not the reverse.  

https://app.swaggerhub.com/help/integrations/github-sync

<img width="691" alt="Screen Shot 2020-05-01 at 2 12 58 PM" src="https://user-images.githubusercontent.com/595967/80842419-597e9c80-8bb6-11ea-96fc-41d7ee74809a.png">

**Comment by MatthewSteeples** [comment]
Hmm, I'll get back to you on that next week then. I've not actually looked into it personally but was going off what one of my team said they'd discovered
