### ISSUE TITLE
Workflowmax XPM?

### ISSUE THREAD

**Issue by LiamTrioTech** [XeroAPI/Xero-OpenAPI#277]
Any updates on if Workflow Max v3 api would make it into this specification?

**Comment by SidneyAllen** [comment]
Hi @LiamTrioTech 

Our OpenAPI specs are used to build our client SDKs which only support JSON requests/responses. Since the WorkflowMax currently only supports XML, we won't be adding support for WFM APIs to our client SDKs at this time.

In the meantime, you can use any off the shelf OAuth 2 library to interact with the WorkflowMax API.

PHP
https://devblog.xero.com/use-php-to-connect-with-xero-31945bccd037

.NET
https://devblog.xero.com/getting-started-with-net-xero-oauth2-0-763ba468a916

Ruby
https://devblog.xero.com/xero-oauth-2-with-ruby-313a6ea37989

NodeJS
https://devblog.xero.com/xero-oauth-2-api-whats-new-node-example-94715fc8ff19

Java
https://devblog.xero.com/try-xero-oauth-2-with-java-e9a46683308d
