### ISSUE TITLE
Missing BankStatement Reports?

### ISSUE THREAD

**Issue by MatthewSteeples** [XeroAPI/Xero-OpenAPI#355]
In the [old wrapper](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/Endpoints/ReportsEndpoint.cs) (line 24) there are reports available for Bank Statements. These don't appear to be in the OpenAPI definition and are also missing from the [official docs](https://developer.xero.com/documentation/api/reports).

Is this an oversight or are they obsolete / being phased out?

**Comment by BTPDarren** [comment]
I think they have moved to the BankFeeds API looks like its changed a little also

**Comment by SidneyAllen** [comment]
@MatthewSteeples

The BankStatement report is slated for deprecation in the future (not ETA at this time). We've removed it from our API documentation and don't encourage use of it as it will go away in the future.

We consider our OpenAPI specs as documentation, therefore have not included it to be inline with our developer docs.  Since our SDKs are generated from these OpenAPI specs, the BankStatement report is not included in any of our OAuth2 SDKs.  This doesn't prevent you from rolling your own http call, but we want developers to be aware of our future plans for this report.

**Comment by MatthewSteeples** [comment]
@SidneyAllen Good enough for me thanks. We'll phase them out of our products.
