### ISSUE TITLE
Request: Add/Update budget

### ISSUE THREAD

**Issue by n-pinkerton** [XeroAPI/Xero-OpenAPI#492]
As per comment in this thread: https://github.com/XeroAPI/Xero-OpenAPI/issues/420#issuecomment-850585903.

Most endpoints in the xero api have create/update support, with the notable exception of budgets which is get-only.

Is this any closer to being implemented than it was a year ago?

**Comment by RettBehrens** [comment]
Hi @n-pinkerton our SDKs are built to match API functionality while simplifying the integration process. Currently the [Xero API](https://developer.xero.com/documentation/api/accounting/budgets) only supports GET /Budgets and so that is what the SDKs support. Looking at the [roadmap ticket](https://trello.com/c/CcUicMll/36-retrieve-budgets-including-tracked-budgets) for supporting budgets via the API it does not seem create/update were in scope. I would encourage to add your vote and voice on the topic [here](https://xero.uservoice.com/forums/5528-accounting-api/suggestions/2679841-enter-budgets-via-the-api-both-historical-and-cur).
